version: '2'

volumes:
  pgdb:
      driver: 'local'
services:
  db:
    image: library/postgres
    ports:
      - "5432:5432"
    env_file: .env 
    volumes:
      - pgdb:/var/lib/postgresql/data
    container_name: HerokuSamplePostgres
  web:
    build: .
    image: heroku_sample_app:latest 
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      POSTGRES_HOST: db
      RAILS_ENV: development
      RACK_ENV: develobpment 
    links:
      - db:postgres
    volumes:
      - ./HerokuSampleApp/:/usr/src/HerokuSampleApp/
    container_name: HerokuSampleApp 
    restart: on-failure
    stdin_open: true
    tty: true

